import Foundation

struct SettingsDefaultsState {
    var refreshFrequency: RefreshFrequency
    var adaptiveActivityScanConsent: AdaptiveActivityScanConsent
    var refreshAllProvidersOnMenuOpen: Bool
    var launchAtLogin: Bool
    var debugMenuEnabled: Bool
    var debugDisableKeychainAccess: Bool
    var debugFileLoggingEnabled: Bool
    var debugLogLevelRaw: String?
    var debugLoadingPatternRaw: String?
    var debugKeepCLISessionsAlive: Bool
    var statusChecksEnabled: Bool
    var sessionQuotaNotificationsEnabled: Bool
    var quotaWarningNotificationsEnabled: Bool
    var predictivePaceWarningNotificationsEnabled: Bool
    var quotaWarningThresholdsRaw: [Int]
    var quotaWarningSessionThresholdsRaw: [Int]
    var quotaWarningWeeklyThresholdsRaw: [Int]
    var quotaWarningSessionEnabled: Bool
    var quotaWarningWeeklyEnabled: Bool
    var quotaWarningSoundEnabled: Bool
    var quotaWarningOnScreenAlertEnabled: Bool
    var quotaWarningMarkersVisible: Bool
    var weeklyProgressWorkDays: Int?
    var usageBarsShowUsed: Bool
    var resetTimesShowAbsolute: Bool
    var providerChangelogLinksEnabled: Bool
    var menuBarShowsBrandIconWithPercent: Bool
    var menuBarHidesCritters: Bool
    var menuBarHighContrastOnInactiveDisplays: Bool
    var menuBarDisplayModeRaw: String?
    var menuBarShowsResetTimeWhenExhausted: Bool
    var kiroMenuBarDisplayModeRaw: String?
    var historicalTrackingEnabled: Bool
    var multiAccountMenuLayoutRaw: String
    var menuBarMetricPreferencesRaw: [String: String]
    var storedMenuBarLayout: MenuBarLayout?
    var menuBarLayoutOverridesRaw: [String: MenuBarLayout]
    var menuBarLayoutSizeRaw: String
    var menuBarLayoutGapRaw: String
    var copilotBudgetExtrasEnabled: Bool
    var copilotIconSecondaryWindowIDRaw: String
    var costUsageEnabled: Bool
    var codexLocalSessionCostLedgerEnabled: Bool
    var costUsageHistoryDays: Int
    var costComparisonPeriodsEnabled: Bool
    var costSummaryDisplayStyleRaw: String
    var hidePersonalInfo: Bool
    var randomBlinkEnabled: Bool
    var confettiOnSessionLimitResetsEnabled: Bool
    var confettiOnWeeklyLimitResetsEnabled: Bool
    var menuBarShowsHighestUsage: Bool
    var claudeOAuthKeychainPromptModeRaw: String?
    var claudeOAuthKeychainReadStrategyRaw: String?
    var claudeOAuthDirectKeychainReadAllowed: Bool
    var claudeWebExtrasEnabledRaw: Bool
    var showOptionalCreditsAndExtraUsage: Bool
    var claudeDailyRoutinesUsageVisible: Bool
    var codexSparkUsageVisible: Bool
    var openAIWebAccessEnabled: Bool
    var openAIWebBatterySaverEnabled: Bool
    var backgroundWorkLowPowerModeEnabled: Bool
    var providerStorageFootprintsEnabled: Bool
    var jetbrainsIDEBasePath: String
    var mergeIcons: Bool
    var switcherShowsIcons: Bool
    var mergedMenuLastSelectedWasOverview: Bool
    var mergedOverviewSelectedProvidersRaw: [String]
    var selectedMenuProviderRaw: String?
    var providerDetectionCompleted: Bool
    var providersSortedAlphabetically: Bool
    var appLanguageRaw: String?
    var terminalAppRaw: String?
    var agentSessionsEnabled: Bool
    var agentSessionLabelStyleRaw: String
    var agentSessionsManualHosts: String
    var preferredCurrencyCode: String
    var iCloudSyncEnabled: Bool
    var iCloudSyncIncludeSecrets: Bool
    var iCloudSyncSnapshotsEnabled: Bool
    var iCloudSyncShowFleetAccounts: Bool
    var iCloudSyncDeviceID: String
}
