public enum LogCategories {
    public static func provider(_ provider: UsageProvider, scope: String? = nil) -> String {
        let base = provider == .opencodego ? "opencode-go" : provider.rawValue
        return scope.map { "\(base)-\($0)" } ?? base
    }

    public static let abacusCookie = Self.provider(.abacus, scope: "cookie")
    public static let abacusUsage = Self.provider(.abacus, scope: "usage")
    public static let adaptiveRefresh = "adaptive-refresh"
    public static let amp = Self.provider(.amp)
    public static let antigravity = Self.provider(.antigravity)
    public static let app = "app"
    public static let auggieCLI = "auggie-cli"
    public static let augment = Self.provider(.augment)
    public static let augmentKeepalive = Self.provider(.augment, scope: "keepalive")
    public static let bedrockUsage = Self.provider(.bedrock, scope: "usage")
    public static let browserCookieGate = "browser-cookie-gate"
    public static let claudeCLI = Self.provider(.claude, scope: "cli")
    public static let claudeProbe = Self.provider(.claude, scope: "probe")
    public static let claudeUsage = Self.provider(.claude, scope: "usage")
    public static let codexRPC = Self.provider(.codex, scope: "rpc")
    public static let commandcodeCookie = Self.provider(.commandcode, scope: "cookie")
    public static let commandcodeUsage = Self.provider(.commandcode, scope: "usage")
    public static let configMigration = "config-migration"
    public static let configStore = "config-store"
    public static let confetti = "confetti"
    public static let cookieCache = "cookie-cache"
    public static let cookieHeaderStore = "cookie-header-store"
    public static let copilotTokenStore = Self.provider(.copilot, scope: "token-store")
    public static let creditsPurchase = "creditsPurchase"
    public static let cursorLogin = Self.provider(.cursor, scope: "login")
    public static let deepSeekSettings = Self.provider(.deepseek, scope: "settings")
    public static let deepSeekUsage = Self.provider(.deepseek, scope: "usage")
    public static let deepgramUsage = Self.provider(.deepgram, scope: "usage")
    public static let devin = Self.provider(.devin)
    public static let doubaoUsage = Self.provider(.doubao, scope: "usage")
    public static let elevenLabsUsage = Self.provider(.elevenlabs, scope: "usage")
    public static let geminiProbe = Self.provider(.gemini, scope: "probe")
    public static let grok = Self.provider(.grok)
    public static let hooks = "hooks"
    public static let keychainCache = "keychain-cache"
    public static let keychainMigration = "keychain-migration"
    public static let keychainPreflight = "keychain-preflight"
    public static let keychainPrompt = "keychain-prompt"
    public static let kimiAPI = Self.provider(.kimi, scope: "api")
    public static let kimiCookie = Self.provider(.kimi, scope: "cookie")
    public static let kimiTokenStore = Self.provider(.kimi, scope: "token-store")
    public static let kimiWeb = Self.provider(.kimi, scope: "web")
    public static let kiro = Self.provider(.kiro)
    public static let longcatAPI = Self.provider(.longcat, scope: "api")
    public static let longcatCookie = Self.provider(.longcat, scope: "cookie")
    public static let longcatWeb = Self.provider(.longcat, scope: "web")
    public static let launchAtLogin = "launch-at-login"
    public static let login = "login"
    public static let logging = "logging"
    public static let manusAPI = Self.provider(.manus, scope: "api")
    public static let manusCookie = Self.provider(.manus, scope: "cookie")
    public static let manusWeb = Self.provider(.manus, scope: "web")
    public static let memoryPressure = "memory-pressure"
    public static let minimaxAPITokenStore = Self.provider(.minimax, scope: "api-token-store")
    public static let minimaxCookie = Self.provider(.minimax, scope: "cookie")
    public static let minimaxCookieStore = Self.provider(.minimax, scope: "cookie-store")
    public static let minimaxUsage = Self.provider(.minimax, scope: "usage")
    public static let minimaxWeb = Self.provider(.minimax, scope: "web")
    public static let mimoCookie = Self.provider(.mimo, scope: "cookie")
    public static let moonshotUsage = Self.provider(.moonshot, scope: "usage")
    public static let neuralWattUsage = Self.provider(.neuralwatt, scope: "usage")
    public static let notifications = "notifications"
    public static let notion = Self.provider(.notion)
    public static let openAIWeb = Self.provider(.openai, scope: "web")
    public static let openAIWebview = Self.provider(.openai, scope: "webview")
    public static let ollama = Self.provider(.ollama)
    public static let opencodeUsage = Self.provider(.opencode, scope: "usage")
    public static let opencodeGoUsage = Self.provider(.opencodego, scope: "usage")
    public static let openRouterUsage = Self.provider(.openrouter, scope: "usage")
    public static let perplexityAPI = Self.provider(.perplexity, scope: "api")
    public static let perplexityCookie = Self.provider(.perplexity, scope: "cookie")
    public static let perplexityWeb = Self.provider(.perplexity, scope: "web")
    public static let poeUsage = Self.provider(.poe, scope: "usage")
    public static let providerDetection = "provider-detection"
    public static let providers = "providers"
    public static let qoderCookie = Self.provider(.qoder, scope: "cookie")
    public static let qoderUsage = Self.provider(.qoder, scope: "usage")
    public static let quotaWarningNotifications = "quotaWarningNotifications"
    public static let sessionQuota = "sessionQuota"
    public static let sessionQuotaNotifications = "sessionQuotaNotifications"
    public static let settings = "settings"
    public static let subprocess = "subprocess"
    public static let syntheticTokenStore = Self.provider(.synthetic, scope: "token-store")
    public static let syntheticUsage = Self.provider(.synthetic, scope: "usage")
    public static let t3chat = Self.provider(.t3chat)
    public static let terminal = "terminal"
    public static let tokenAccounts = "token-accounts"
    public static let tokenCost = "token-cost"
    public static let ttyRunner = "tty-runner"
    public static let veniceUsage = Self.provider(.venice, scope: "usage")
    public static let vertexAIFetcher = Self.provider(.vertexai, scope: "fetcher")
    public static let warpUsage = Self.provider(.warp, scope: "usage")
    public static let zed = Self.provider(.zed)
    public static let webkitTeardown = "webkit-teardown"
    public static let zaiSettings = Self.provider(.zai, scope: "settings")
    public static let zaiTokenStore = Self.provider(.zai, scope: "token-store")
    public static let zaiUsage = Self.provider(.zai, scope: "usage")
    public static let stepfunUsage = Self.provider(.stepfun, scope: "usage")
    public static let zoommate = Self.provider(.zoommate)
}
