import CodexBarCore
import Foundation

/// Closed first-party bootstrap list. Runtime/plugin registrations remain owned by
/// `ProviderImplementationRegistry.register(_:)`.
enum ProviderImplementationManifest {
    static let makeImplementations: [@Sendable () -> any ProviderImplementation] = [
        { CodexProviderImplementation() },
        { OpenAIAPIProviderImplementation() },
        { AzureOpenAIProviderImplementation() },
        { ClaudeProviderImplementation() },
        { ClinePassProviderImplementation() },
        { CursorProviderImplementation() },
        { OpenCodeProviderImplementation() },
        { OpenCodeGoProviderImplementation() },
        { AlibabaCodingPlanProviderImplementation() },
        { AlibabaTokenPlanProviderImplementation() },
        { QwenCloudProviderImplementation() },
        { FactoryProviderImplementation() },
        { GeminiProviderImplementation() },
        { AntigravityProviderImplementation() },
        { CopilotProviderImplementation() },
        { DevinProviderImplementation() },
        { ZaiProviderImplementation() },
        { MiniMaxProviderImplementation() },
        { ManusProviderImplementation() },
        { KimiProviderImplementation() },
        { KiloProviderImplementation() },
        { KiroProviderImplementation() },
        { VertexAIProviderImplementation() },
        { AugmentProviderImplementation() },
        { JetBrainsProviderImplementation() },
        { MoonshotProviderImplementation() },
        { AmpProviderImplementation() },
        { T3ChatProviderImplementation() },
        { OllamaProviderImplementation() },
        { SyntheticProviderImplementation() },
        { OpenRouterProviderImplementation() },
        { ElevenLabsProviderImplementation() },
        { WarpProviderImplementation() },
        { WindsurfProviderImplementation() },
        { ZedProviderImplementation() },
        { PerplexityProviderImplementation() },
        { MiMoProviderImplementation() },
        { DoubaoProviderImplementation() },
        { SakanaProviderImplementation() },
        { AbacusProviderImplementation() },
        { MistralProviderImplementation() },
        { DeepSeekProviderImplementation() },
        { DeepInfraProviderImplementation() },
        { CodebuffProviderImplementation() },
        { CrofProviderImplementation() },
        { VeniceProviderImplementation() },
        { CommandCodeProviderImplementation() },
        { QoderProviderImplementation() },
        { StepFunProviderImplementation() },
        { BedrockProviderImplementation() },
        { GrokProviderImplementation() },
        { GroqProviderImplementation() },
        { LLMProxyProviderImplementation() },
        { LiteLLMProviderImplementation() },
        { DeepgramProviderImplementation() },
        { PoeProviderImplementation() },
        { ChutesProviderImplementation() },
        { NeuralWattProviderImplementation() },
        { ClawRouterProviderImplementation() },
        { LongCatProviderImplementation() },
        { Sub2APIProviderImplementation() },
        { WayfinderProviderImplementation() },
        { ZenMuxProviderImplementation() },
        { AiAndProviderImplementation() },
        { ZoomMateProviderImplementation() },
        { XAIProviderImplementation() },
        { NotionProviderImplementation() },
    ]
}
